### ISSUE TITLE
Attaching data to resource

### ISSUE THREAD

**Issue by mnichols** [pmoule/go2hal#1]
Hey thanks for this library!
One question is the simplest way to assign data directly to the resource body. Right now you call `.Data()` but it seems to force us to map each property of a struct manually to that instance of the `map` ? 
I wondered how you got around this limitation without requiring a node on the body for assignment; eg
```
type MyStruct struct {
Name string
}

// instead of
body := res.Data()
body["name"] = myStructInstance.Name

// or
body["data"] = myStructInstance
```

Any insights?

**Comment by pmoule** [comment]
Hey Mike!

You are right, it is a limitation. Since I use a map at least one node e.g. 'data' is required.
This leads to (maybe, not wanted) JSON like:

```
"data": {
          "name": "Patrick"
}
```

I agree, it's a bit cumbersome to force a manual property mapping. Especially when you prepared your DTOs. 

Instead of calling ``bytes, error := encoder.ToJSON(root)``
a workaround might be eg

```
properties := hal.PropertyMap{}

links := halResource.Links()
embedded := halResource.EmbeddedResources()

properties[links.Name] = links.Content
properties[embedded.Name] = embedded.Content

//this requires to add a node named 'data' with your DTO assigned.
data := halResource.Data()["data"]
//use Indirect() when assigned value is a ptr
val := reflect.Indirect(reflect.ValueOf(data))

for i := 0; i < val.NumField(); i++ {
	//look out, no camel casing when field identifiers are exported!
	properties[val.Type().Field(i).Name] = val.Field(i).Interface()
}

bytes, err := json.Marshal(properties)
```

Best regards
Patrick

**Comment by pmoule** [comment]
an even more convenient option solving the camelcase issue:
```
func toJSON(halResource hal.Resource, dataKey string) ([]byte, error) {
	links := halResource.Links()
	embedded := halResource.EmbeddedResources()
	
	properties := hal.PropertyMap{}
	properties[links.Name] = links.Content
	properties[embedded.Name] = embedded.Content

	data := halResource.Data()[dataKey]
	
	if data == nil {
		return json.Marshal(properties)
	}

	val := reflect.Indirect(reflect.ValueOf(data))

	for i := 0; i < val.NumField(); i++ {
		fieldName, ok := val.Type().Field(i).Tag.Lookup("json")

		if !ok || fieldName == "-" {
			continue
		}

		properties[fieldName] = val.Field(i).Interface()
	}

	return json.Marshal(properties)
}
```

But this works on a resource's top level, only. Embedded resources still require a manual property mapping. I plan providing a more convenient solution with the next **go2hal** release. Maybe, this month.

**Comment by pmoule** [comment]
issue closed with v0.3.0 release

**Comment by mnichols** [comment]
Excellent approach. I apologize for just now returning to this...we've been heads down on a release.
I'm going to bump us up to v0.3.0! By the way this is being used at InVisionApp :)

**Comment by pmoule** [comment]
:)
