### ISSUE TITLE
time.Time vs *time.Time

### ISSUE THREAD

**Issue by jbpineiroc** [pmoule/go2hal#2]
When I use the data type time.Time as value I get an error, but when I use it as a pointer it works fine.

```
package main

import (
	"fmt"
	"time"

	"github.com/pmoule/go2hal/hal"
)

type test struct {
	Timestamp time.Time `json:"timestamp,omitempty"`
}

func main() {
	t := &test{Timestamp: time.Now()}
	root := hal.NewResourceObject()
	root.AddData(t)
	bytes, _ := hal.NewEncoder().ToJSON(root)
	fmt.Println(string(bytes))
}
```
----------------------------------------------------------------------------------------------------
```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x10be7e0, 0xc42000a2c0, 0x1a6, 0xffffffffffffff01, 0xc420041ca0, 0x109d9e8)
        /usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:936 +0x1a5
reflect.Value.Interface(0x10be7e0, 0xc42000a2c0, 0x1a6, 0x9, 0xc420041ce0)
        /usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:925 +0x44
github.com/pmoule/go2hal/hal.isZeroValue(0x10be7e0, 0xc42000a2c0, 0x1a6, 0x0)
        /Users/jbpineiroc/go/src/github.com/pmoule/go2hal/hal/resourceobject.go:121 +0x162
github.com/pmoule/go2hal/hal.isZeroValue(0x10dfb60, 0xc42000a2c0, 0x199, 0x9)
        /Users/jbpineiroc/go/src/github.com/pmoule/go2hal/hal/resourceobject.go:109 +0x2e4
github.com/pmoule/go2hal/hal.(*resourceObject).readDataFields(0xc42000a2e0, 0x10c9e20, 0xc42000a2c0, 0x199)
        /Users/jbpineiroc/go/src/github.com/pmoule/go2hal/hal/resourceobject.go:91 +0x36b
github.com/pmoule/go2hal/hal.(*resourceObject).AddData(0xc42000a2e0, 0x10b8d00, 0xc42000a2c0)
        /Users/jbpineiroc/go/src/github.com/pmoule/go2hal/hal/resourceobject.go:49 +0x66
main.main()
        /Users/jbpineiroc/go/src/xxxxx/xxxxxxx/test/main.go:17 +0x1ae
exit status 2
```

=========================================================================
```
package main

import (
	"fmt"
	"time"

	"github.com/pmoule/go2hal/hal"
)

type test struct {
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

func main() {
	k := time.Now()
	t := &test{Timestamp: &k}
	root := hal.NewResourceObject()
	root.AddData(t)
	bytes, _ := hal.NewEncoder().ToJSON(root)
	fmt.Println(string(bytes))
}
```
----------------------------------------------------------------------------------------------------
`{"timestamp":"2017-09-12T00:00:39.063678084-05:00"}`

**Comment by pmoule** [comment]
Hi,

time.Time has no exported fields. This is why checking for a zero value fails  => panic
As time.Time has a special definition of a zero value, I can provide a workaround for time.Time. But same issue will occur for other types with unexported fields.

For now, using pointers is safe as a zero value check is simple. I'll check for providing a solution on this issue.

Best regards
Patrick

**Comment by pmoule** [comment]
check new branch: https://github.com/pmoule/go2hal/tree/ftr_timevalues

Changes:
time.Time works when used as value, now.
Struct fields must be flagged with json tag if they should be mapped, else they are omitted.
Same for fields of embedded types and fields of any other struct used in root struct.

Best regards
Patrick
