### ISSUE TITLE
null json encoding when resources is empty slice

### ISSUE THREAD

**Issue by yanielv** [pmoule/go2hal#3]
If we have embedded resources ... eg. doctors, which is a element list and we set the resources passing empty slice, the result when json encoding executes isn´t what we expect...

Expected result:
```json
{
    "_links": {
        "self": {
            "href": "/docwhoapi/doctors"
        }
    },
    "_embedded": {
        "doctors": []
    },
```
Result:
```json
{
    "_links": {
        "self": {
            "href": "/docwhoapi/doctors"
        }
    },
    "_embedded": {
        "doctors": null
    },
```

Resolved:
https://github.com/yanielv/go2hal/commit/a0e203e5f58bc014e2075da075befdbc92c207eb

**Comment by pmoule** [comment]
Hi,

this is already fixed 
(commit: https://github.com/pmoule/go2hal/commit/9e2f7fd0c08b92359643de1fc27d20b07edd83eb)

A new release is planned ~start of October.

Best regards
Patrick

**Comment by yanielv** [comment]
Oh ! Perfect !
Best regard !!
