### ISSUE TITLE
Panic when using AddData() with pointers

### ISSUE THREAD

**Issue by yanielv** [pmoule/go2hal#4]
Problem with `AddData(info)` when `info` is a pointer and it has an embedded field as pointer too. In some way, readDataFields(v reflect.Value) fails retrieving fields of embedded struct, because of call to readDataFields(vField.Addr()), resulting in give to the method a pointer of pointer...

The problem can be solved in this way:
```golang
for i := 0; i < vType.NumField(); i++ {
		tField := vType.Field(i)
		vField := v.Field(i)
               
                // do the same checking step as readDataFields method does in the beginning
		if vField.Kind() == reflect.Ptr {
			vField = vField.Elem()
		}

		if !vField.CanInterface() {
			continue
		}

		if tField.Anonymous {
			if !vField.CanAddr() {
				anonymValue := reflect.ValueOf(vField.Interface())
				readDataFields(anonymValue)
				continue
			}

			readDataFields(vField.Addr())
		}
               ...
```

**Comment by pmoule** [comment]
Hi,

this is an issue, indeed. Thanks! Additionally handling of a pointer's zero value is required.
see fda1d58a0b13ca8d96eefa63c2eb095382e6ac85

Best regards
Patrick
