### ISSUE TITLE
"go get github.com/pmoule/go2hal" isn't working because of project layout

### ISSUE THREAD

**Issue by ndwyer-paa** [pmoule/go2hal#5]
I'm fairly new to go but I believe the go get isn't working because of project layout in github....This is what I get: 

> nick@nick-workhorse:~/code/test/api$ go get github.com/pmoule/go2hal
> can't load package: package github.com/pmoule/go2hal: no Go files in /home/nick/code/test/api/src/github.com/pmoule/go2hal
>

**Comment by ndwyer-paa** [comment]
It should actually be `go get github.com/pmoule/go2hal/hal`

**Comment by pmoule** [comment]
:) Thanks for the hint. Changed the README

Cheers
Patrick
