### ISSUE TITLE
Support inlining Templaes in a Resource

### ISSUE THREAD

**Issue by sazzer** [pmoule/go2hal#9]
Strictly speaking, this library correctly follows what's laid out by the HAL and HAL-FORMS specs, especially with regards to the two being separate.

However, in my experience this isn't necessary. Most HAL and HAL-FORMS clients that I've used can correctly understand when the `_templates` are inlined directly into the original resource instead of being a separate HTTP request.

Being able to do this is then much more convenient -  you don't need additional handlers on the server, and you don't need additional network calls from the client - and it's much easier for the templates to directly relate to the resource that they represent (e.g. offering certain fields or attributes based on the current state of this resource, instead of always being the same).

Would there be any possibility of extending this library to support that?

Cheers

**Comment by pmoule** [comment]
Hi Graham

thanks for the request.

`go2hal` is intended to be not too restrictive, so your request about combining responses of HAL and HAL-FORMS wrt `_templates` is absolutely valid. Will look for a way about how this could be enabled. It's on my list, but it might take a few days.

Best wishes
Patrick

**Comment by pmoule** [comment]
Hi Graham

it's already possible to combine responses without breaking the constraint that _HAL-FORMS_ documents should always be sent over HTTP using the `application/prs.hal-forms+json` media type identifer.

To achieve this, you can make use of the `AddData(interface{})` method of `hal.Resource` interface.

**Example:**
```
type DataContainer struct {
	Templates TemplateContainer `json:"_templates"`
}

type TemplateContainer struct {
	Default halforms.Template `json:"default"`
	Other   halforms.Template `json:"anyotherkey"`
}

func doctors(w http.ResponseWriter, r *http.Request) {
	factory := hal.NewResourceFactory([]*hal.LinkObject{})
	self := "/docwhoapi/doctors"
	halResource := factory.CreateRootResource(self)

	template := halforms.NewTemplate()
	template.Method = http.MethodPost
	template.Target = "/docwhoapi/doctors"

	templateContainer := TemplateContainer{Default: *template, Other: *template}
	data := DataContainer{Templates: templateContainer}
	halResource.AddData(data)

	sendResponse(w, http.StatusOK, halResource)
}

func sendResponse(w http.ResponseWriter, statusCode int, halResource hal.Resource) {
	...
}
```

This outputs the following _JSON_ :
```
{
  "_links": {
    "curies": [],
    "self": {
      "href": "/docwhoapi/doctors"
    }
  },
  "_templates": {
    "anyotherkey": {
      "contentType": "application/json",
      "key": "default",
      "method": "POST",
      "properties": [],
      "target": "/docwhoapi/doctors",
      "title": "default"
    },
    "default": {
      "contentType": "application/json",
      "key": "default",
      "method": "POST",
      "properties": [],
      "target": "/docwhoapi/doctors",
      "title": "default"
    }
  }
}
```

The only drawback would be, to care about the correct mapping of a template's key and the _JSON_ property name, to have both consistent. 

Does this help reducing network calls?

Best wishes
Patrick

**Comment by pmoule** [comment]
closing
